version: '3.7'
services:
  front-end:
    image: leograba/pasta-demo-credentials-setup-front:latest-arm32v7
    depends_on:
      - back-end
    ports:
      - "8080:80"
    links:
      - back-end
    networks:
      - configsetup
  back-end:
    image: leograba/pasta-demo-credentials-setup-back:latest-arm32v7
    networks:
      - configsetup
    volumes:
      - type: bind
        source: /greengrass/config/
        target: /greengrass/config/
      - type: bind
        source: /greengrass/certs/
        target: /greengrass/certs/
      - type: bind
        source: /proc/device-tree/model
        target: /setup_descripion
        read_only: true
networks:
  configsetup: