version: '3.7'
services:
  front-end:
    image: torizonextras/pasta-demo-credentials-setup-front:latest-arm64v8
    depends_on:
      - back-end
    ports:
      - "8820:80"
    links:
      - back-end
    networks:
      - configsetup
  back-end:
    image: torizonextras/pasta-demo-credentials-setup-back:latest-arm64v8
    networks:
      - configsetup
    volumes:
      - type: bind
        source: /run/systemd
        target: /run/systemd
      - type: bind
        source: /etc/greengrass/
        target: /etc/greengrass/
      - type: bind
        source: /greengrass/config/
        target: /greengrass/config/
      - type: bind
        source: /greengrass/certs/
        target: /greengrass/certs/
      - type: bind
        source: /proc/device-tree/model
        target: /setup_descripion
        read_only: true
networks:
  configsetup:
