version: '3.7'
services:
  system-info:
    image: leograba/pasta-demo-system-info:latest-arm64v8
    ports:
      - "5001:5001"
    volumes:
      - type: bind
        source: /sys
        target: /sys
        read_only: true