version: '3.7'
services:
  inference:
    image: matheuscastello/inference:latest-arm64v8
    volumes:
      - type: bind
        source: /sys
        target: /sys
      - type: bind
        source: /tmp
        target: /tmp
      - type: bind
        source: /dev
        target: /dev
    network_mode: "host"
    privileged: "true"